clean up if ffmpeg error

diff --git a/videoaip b/videoaip
--- a/videoaip
+++ b/videoaip
@@ -154,7 +154,13 @@ mkdir "${targetdirectory}/${mediaid}/objects/access"
 mediainfo --output=XML "$file_input" > "${targetdirectory}/${mediaid}/logs/fileMeta/${mediaid}.xml"
 mediainfo "$file_input" > "${targetdirectory}/${mediaid}/logs/fileMeta/${mediaid}.txt"
 if ! [ -e "$mp4_name" ] ; then
-    ffmpeg ${STARTTRIMOPT} -i "${file_input}" -c:v libx264 -pix_fmt yuv420p -movflags +faststart -preset fast -crf 18 -c:a aac -ar 48k -b:a 128k -vf yadif=deint=1"${cropoptions}" ${ENDTRIMOPT} "$mp4_name" 
+    ffmpeg ${STARTTRIMOPT} -i "${file_input}" -c:v libx264 -pix_fmt yuv420p -movflags +faststart -preset fast -crf 18 -c:a aac -ar 48k -b:a 128k -vf yadif=deint=1"${cropoptions}" ${ENDTRIMOPT} "$mp4_name"
+    if [ "${?}" -ne 0 ] ; then
+        echo -e "\033[1;31mError in Conversion! Cleaning up and Exiting.\033[0m"
+        rm "$mp4_name"
+        rm -r "${targetdirectory}/${mediaid}"
+        exit 1
+    fi
 fi
 #sync access mp4 if selected
 if [[ "${derivative_choice}" = "Y" ]] ; then
